### ISSUE TITLE
可以参考alpaca(国外的免佣金券商)的API接口

### ISSUE THREAD

**Issue by zfsamzfsam** [MuggleWei/babel-trader#1]
https://github.com/alpacahq/alpaca-trade-api-go
https://github.com/alpacahq/alpaca-trade-api-python
https://github.com/alpacahq/alpaca-trade-api-js
https://github.com/alpacahq/alpaca-trade-api-csharp

**Comment by MuggleWei** [comment]
看了一下你说的库，对本项目参考意义可能不大。
babel-trader其实是我自己的交易系统上手服务的部分，因为觉得这部分会比较通用，所以整理了一下开源出来，但是主要还是满足自己的需求。 我的系统有对接okex，和你说的接口风格会比较类似，因为okex现在api要升级v3，所以我打算升级完之后再整合过来。如果你需要上面的接口转换到babel-trader，到时可参考一下，也欢迎贡献代码。
