### ISSUE TITLE
有没有计划支持实盘易的接口？

### ISSUE THREAD

**Issue by bigplum** [MuggleWei/babel-trader#2]
rt

**Comment by MuggleWei** [comment]
= = ？？？ ！
这本来就是可以直接实盘跑的啊！我现在okex和ctp都在跑呢。 配置文件填实盘账户，密码，跑起来就可以了，看下doc文件夹里写的。 要注意的是，okex的服务要放在墙外跑，xtp的实盘，当前合规要求，还是要联系券商机房托管的，有资金门槛，你可以联系下中泰证券的人。

**Comment by MuggleWei** [comment]
首先，这本来就支持实盘交易，在配置文件中填入正确的配置即可。 注意okex的服务要在墙外跑，xtp要联系下中泰证券，当前券商合规的要求，还是要机房托管呢，有资金门槛。
其次，babel-trader是封装了 ctp, okex 和 xtp，提供了 ws和rest服务，和语言无关，易语言也可以直接连接，我自己并不熟悉易语言，所以没有写相关demo，欢迎提交 易语言连接的demo。

**Comment by bigplum** [comment]
不好意思，我没说清楚，是这个：http://www.iguuu.com/e#api

用这个接口来做自动交易，还是挺方便的。

**Comment by MuggleWei** [comment]
看了一下那个网站，并没有计划去封装那个接口呢。
