### ISSUE TITLE
段错误

### ISSUE THREAD

**Issue by zhuzhenping** [MuggleWei/babel-trader#4]
系统：debian10，git clone下载代码，编译成功，运行时提示错误：
$ ./babeltrader-ctp-quote 
段错误

经调试，可能运行到下面这一句时出错：
	// run ctp handler
	CTPQuoteHandler handler(conf);

找不到原因。

**Comment by MuggleWei** [comment]
感谢你的反馈，请问有具体的dump信息吗？ 没有具体的信息，可能会比较难定位错误呢

zhuzhenping <notifications@github.com> 于2020年9月9日周三 上午6:10写道：

**Comment by MuggleWei** [comment]
感谢反馈，请问有具体的dump信息吗？
这句Quote应该还没有处于运行状态，这时候崩掉有点儿奇怪，可以gdb调试一下，看下当时的内存里的内容是什么个情况

**Comment by zhuzhenping** [comment]
gdb调试结果如下：
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7050ee0 in pthread_rwlock_wrlock () from /lib/x86_64-linux-gnu/libpthread.so.0

搜索网络，暂时没有找到答案。

**Comment by MuggleWei** [comment]
这个是因为uWS引用了本地的openssl，而ctp直接包含了openssl，当两边引用了不同版本的openssl库时，会出现这个问题。而当前使用的uWS版本中，又没有接口去关闭掉ssl功能。推荐在release中拿编译好的版本，包里面可以看到libssl.so.1.0.0，改一下cmake，强制链接1.0.0版本的ssl。

后期uWS升级之后，接口变动比较大，就不想跟那边的进度了。 现在有在准备写自己的ws库，写好就直接替换掉当前的ws库，就彻底杜绝这个问题了。
